---

- name: Installs Docker required packages
  apt:
    name="{{ pkgs }}" state=present
  vars:
    pkgs:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python3-docker

- name: Get APT key
  apt_key:
    data: "{{ lookup('file', 'docker-apt.asc') }}"
    state: "present"

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: "present"
    update_cache: True

- name: Install docker and docker-compose
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=True
    install_recommends=False
  vars:
    pkgs:
    - docker-ce
    - docker-compose

- name: Create daemon.json
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json owner=root group=root mode=0644
  register: daemon_settings

- name: Create folder for systemd settings
  file: path=/etc/systemd/system/docker.service.d/ state=directory

- name: Set proxy settings
  template: src=http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf owner=root group=root mode=0644
  register: proxy_settings

- name: Restart docker service
  service: name=docker state=restarted enabled=yes daemon_reload=yes
  when: daemon_settings.changed or proxy_settings.changed

